# Generated by Django 6.1 on 2026-08-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('uploaded', 'Uploaded'), ('edited', 'Edited'), ('deleted', 'Deleted')], max_length=20)),
                ('performed_by', models.CharField(max_length=150)),
                ('document_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
