# Generated by Django 6.1 on 2026-09-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_uploadedpdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedpdf',
            options={'ordering': ['-created_at'], 'verbose_name': 'Uploaded PDF', 'verbose_name_plural': 'All Uploaded PDFs'},
        ),
    ]
